name: CI

# Triggers: cuándo corre el pipeline

on:
  push:
    branches: ["master", "developer"]
  pull_request:
    branches: ["master"]

# Permisos del workflow
permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    # Aquí GitHub Actions levanta un contenedor MongoDB como “servicio” para tus tests.
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MONGO_URI_TEST: mongodb://localhost:27017
      DB_NAME_TEST: my_super_library_test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

  docker_build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/developer')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/my-super-library:latest
            ghcr.io/${{ github.repository_owner }}/my-super-library:${{ github.sha }}

      - name: Trigger Render deploy
        if: env.RENDER_DEPLOY_HOOK_URL != ''
        run: curl -fsS -X POST "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
